"
I represent a boolean type
"
Class {
	#name : #FASTJavaBooleanTypeExpression,
	#superclass : #FASTJavaEntity,
	#traits : 'FASTTBooleanLiteral',
	#classTraits : 'FASTTBooleanLiteral classTrait',
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaBooleanTypeExpression class >> annotation [

	<FMClass: #BooleanTypeExpression super: #FASTJavaEntity>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]
