"
I represent a char type
"
Class {
	#name : #FASTJavaCharTypeExpression,
	#superclass : #FASTJavaPrimitiveTypeExpression,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaCharTypeExpression class >> annotation [

	<MSEClass: #CharTypeExpression super: #FASTJavaPrimitiveTypeExpression>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaCharTypeExpression class >> generatedSlotNames [
	<generated>
	'FASTJavaCharTypeExpression class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaCharTypeExpression class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaCharTypeExpression class >> requirements [

	<generated>
	^ {  }
]
