"
I'm a factice entity that is used by JavaNewClassExpression to represents the defined method of a class
"
Class {
	#name : #FASTJavaNewClassMethodStatment,
	#superclass : #FASTStatement,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaNewClassMethodStatment class >> annotation [

	<MSEClass: #NewClassMethodStatment super: #FASTStatement>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaNewClassMethodStatment class >> generatedSlotNames [
	<generated>
	'FASTJavaNewClassMethodStatment class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaNewClassMethodStatment class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaNewClassMethodStatment class >> requirements [

	<generated>
	^ {  }
]
