"
I represent a float type
"
Class {
	#name : #FASTJavaFloatTypeExpression,
	#superclass : #FASTJavaPrimitiveTypeExpression,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaFloatTypeExpression class >> annotation [

	<MSEClass: #FloatTypeExpression super: #FASTJavaPrimitiveTypeExpression>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaFloatTypeExpression class >> generatedSlotNames [
	<generated>
	'FASTJavaFloatTypeExpression class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaFloatTypeExpression class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaFloatTypeExpression class >> requirements [

	<generated>
	^ {  }
]
