"
A statement to be evaluated in the loop
"
Class {
	#name : #FASTJavaBodyStatement,
	#superclass : #FASTStatement,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaBodyStatement class >> annotation [

	<MSEClass: #BodyStatement super: #FASTStatement>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaBodyStatement class >> generatedSlotNames [
	<generated>
	'FASTJavaBodyStatement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaBodyStatement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaBodyStatement class >> requirements [

	<generated>
	^ {  }
]
