Class {
	#name : #FASTJavaOperationLeftOperand,
	#superclass : #FASTExpression,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaOperationLeftOperand class >> annotation [

	<MSEClass: #OperationLeftOperand super: #FASTExpression>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaOperationLeftOperand class >> generatedSlotNames [
	<generated>
	'FASTJavaOperationLeftOperand class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaOperationLeftOperand class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaOperationLeftOperand class >> requirements [

	<generated>
	^ {  }
]
