"
I represent a boolean literal node.
"
Class {
	#name : #FASTJavaBooleanLiteral,
	#superclass : #FASTJavaLiteral,
	#traits : 'FASTTLiteral',
	#classTraits : 'FASTTLiteral classTrait',
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaBooleanLiteral class >> annotation [

	<FMClass: #BooleanLiteral super: #FASTJavaLiteral>
	<package: #'FAST-Java-Model'>
	<generated>
	^ self
]
