Class {
	#name : #FASTJavaConditionStatement,
	#superclass : #FASTStatement,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaConditionStatement class >> annotation [

	<MSEClass: #ConditionStatement super: #FASTStatement>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaConditionStatement class >> generatedSlotNames [
	<generated>
	'FASTJavaConditionStatement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaConditionStatement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaConditionStatement class >> requirements [

	<generated>
	^ {  }
]
