Class {
	#name : #FASTJavaExpressionStatement,
	#superclass : #FASTJavaEntity,
	#traits : 'FASTTExpressionStatement',
	#classTraits : 'FASTTExpressionStatement classTrait',
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaExpressionStatement class >> annotation [

	<FMClass: #ExpressionStatement super: #FASTJavaEntity>
	<package: #'FAST-Java-Model'>
	<generated>
	^ self
]
