"
Java integer literal node
"
Class {
	#name : #FASTJavaIntegerLiteral,
	#superclass : #FASTLiteral,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaIntegerLiteral class >> annotation [

	<MSEClass: #IntegerLiteral super: #FASTLiteral>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaIntegerLiteral class >> generatedSlotNames [
	<generated>
	'FASTJavaIntegerLiteral class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaIntegerLiteral class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaIntegerLiteral class >> requirements [

	<generated>
	^ {  }
]
