"
I represent an int type
"
Class {
	#name : #FASTJavaIntTypeExpression,
	#superclass : #FASTJavaPrimitiveTypeExpression,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaIntTypeExpression class >> annotation [

	<MSEClass: #IntTypeExpression super: #FASTJavaPrimitiveTypeExpression>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaIntTypeExpression class >> generatedSlotNames [
	<generated>
	'FASTJavaIntTypeExpression class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaIntTypeExpression class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaIntTypeExpression class >> requirements [

	<generated>
	^ {  }
]
