"
ExpressionStatements evaluated at the end of each loop
"
Class {
	#name : #FASTJavaIncrementorsStatement,
	#superclass : #FASTStatement,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaIncrementorsStatement class >> annotation [

	<MSEClass: #IncrementorsStatement super: #FASTStatement>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaIncrementorsStatement class >> generatedSlotNames [
	<generated>
	'FASTJavaIncrementorsStatement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaIncrementorsStatement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaIncrementorsStatement class >> requirements [

	<generated>
	^ {  }
]
