Class {
	#name : #FASTJavaModel,
	#superclass : #MooseModel,
	#category : #'FAST-Java-Model'
}

{ #category : #accessing }
FASTJavaModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits' #'FAST-Core-Model')
]

{ #category : #meta }
FASTJavaModel class >> annotation [
	<MSEClass: #FASTJavaModel super: #MooseModel>
	<package: #'FAST-Java-Model'>
	<generated>
]
