"
I represent a boolean type
"
Class {
	#name : #FASTJavaBooleanTypeExpression,
	#superclass : #FASTJavaPrimitiveTypeExpression,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaBooleanTypeExpression class >> annotation [

	<MSEClass: #BooleanTypeExpression super: #FASTJavaPrimitiveTypeExpression>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaBooleanTypeExpression class >> generatedSlotNames [
	<generated>
	'FASTJavaBooleanTypeExpression class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaBooleanTypeExpression class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaBooleanTypeExpression class >> requirements [

	<generated>
	^ {  }
]
