"
A FASTJavaIdentifier is an identifier in a Java program
"
Class {
	#name : #FASTJavaIdentifier,
	#superclass : #FASTJavaVariableExpression,
	#traits : 'FASTJavaTReceiver',
	#classTraits : 'FASTJavaTReceiver classTrait',
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaIdentifier class >> annotation [

	<FMClass: #Identifier super: #FASTJavaVariableExpression>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]
