Class {
	#name : #FASTJavaThenPartStatement,
	#superclass : #FASTStatement,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaThenPartStatement class >> annotation [

	<MSEClass: #ThenPartStatement super: #FASTStatement>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaThenPartStatement class >> generatedSlotNames [
	<generated>
	'FASTJavaThenPartStatement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaThenPartStatement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaThenPartStatement class >> requirements [

	<generated>
	^ {  }
]
