"
I represent a short type
"
Class {
	#name : #FASTJavaShortTypeExpression,
	#superclass : #FASTJavaPrimitiveTypeExpression,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaShortTypeExpression class >> annotation [

	<MSEClass: #ShortTypeExpression super: #FASTJavaPrimitiveTypeExpression>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaShortTypeExpression class >> generatedSlotNames [
	<generated>
	'FASTJavaShortTypeExpression class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaShortTypeExpression class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaShortTypeExpression class >> requirements [

	<generated>
	^ {  }
]
