"
I represent a long type
"
Class {
	#name : #FASTJavaLongTypeExpression,
	#superclass : #FASTJavaPrimitiveTypeExpression,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaLongTypeExpression class >> annotation [

	<MSEClass: #LongTypeExpression super: #FASTJavaPrimitiveTypeExpression>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaLongTypeExpression class >> generatedSlotNames [
	<generated>
	'FASTJavaLongTypeExpression class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaLongTypeExpression class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaLongTypeExpression class >> requirements [

	<generated>
	^ {  }
]
