"
A FASTJavaThis corresponds to 'this' in Java
"
Class {
	#name : #FASTJavaThis,
	#superclass : #FASTVariableExpression,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaThis class >> annotation [

	<MSEClass: #This super: #FASTVariableExpression>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaThis class >> generatedSlotNames [
	<generated>
	'FASTJavaThis class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaThis class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaThis class >> requirements [

	<generated>
	^ {  }
]
