Class {
	#name : #FASTJavaOperationRightOperand,
	#superclass : #FASTExpression,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaOperationRightOperand class >> annotation [

	<MSEClass: #OperationRightOperand super: #FASTExpression>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaOperationRightOperand class >> generatedSlotNames [
	<generated>
	'FASTJavaOperationRightOperand class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaOperationRightOperand class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaOperationRightOperand class >> requirements [

	<generated>
	^ {  }
]
