"
I represent a primitive type
"
Class {
	#name : #FASTJavaPrimitiveTypeExpression,
	#superclass : #FASTJavaTypeExpression,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaPrimitiveTypeExpression class >> annotation [

	<MSEClass: #PrimitiveTypeExpression super: #FASTJavaTypeExpression>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaPrimitiveTypeExpression class >> generatedSlotNames [
	<generated>
	'FASTJavaPrimitiveTypeExpression class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaPrimitiveTypeExpression class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaPrimitiveTypeExpression class >> requirements [

	<generated>
	^ {  }
]
