"
I represent a double type
"
Class {
	#name : #FASTJavaDoubleTypeExpression,
	#superclass : #FASTJavaPrimitiveTypeExpression,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaDoubleTypeExpression class >> annotation [

	<MSEClass: #DoubleTypeExpression super: #FASTJavaPrimitiveTypeExpression>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaDoubleTypeExpression class >> generatedSlotNames [
	<generated>
	'FASTJavaDoubleTypeExpression class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaDoubleTypeExpression class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaDoubleTypeExpression class >> requirements [

	<generated>
	^ {  }
]
