"
I represent a short type
"
Class {
	#name : #FASTJavaVoidTypeExpression,
	#superclass : #FASTJavaPrimitiveTypeExpression,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaVoidTypeExpression class >> annotation [

	<MSEClass: #VoidTypeExpression super: #FASTJavaPrimitiveTypeExpression>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaVoidTypeExpression class >> generatedSlotNames [
	<generated>
	'FASTJavaVoidTypeExpression class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaVoidTypeExpression class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaVoidTypeExpression class >> requirements [

	<generated>
	^ {  }
]
