Class {
	#name : #FASTJavaUnknownSourceLanguage,
	#superclass : #FASTJavaSourceLanguage,
	#traits : 'FamixTSourceLanguage',
	#classTraits : 'FamixTSourceLanguage classTrait',
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaUnknownSourceLanguage class >> annotation [

	<MSEClass: #UnknownSourceLanguage super: #FASTJavaSourceLanguage>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]
