Class {
	#name : #FASTJavaUnknownSourceLanguage,
	#superclass : #FASTJavaSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FASTJavaSourceLanguage>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]
