"
I represent a type of Array
"
Class {
	#name : #FASTJavaArrayType,
	#superclass : #FASTVariableExpression,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaArrayType class >> annotation [

	<MSEClass: #ArrayType super: #FASTVariableExpression>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaArrayType class >> generatedSlotNames [
	<generated>
	'FASTJavaArrayType class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaArrayType class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaArrayType class >> requirements [

	<generated>
	^ {  }
]
