"
I represent a byte type
"
Class {
	#name : #FASTJavaByteTypeExpression,
	#superclass : #FASTJavaPrimitiveTypeExpression,
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaByteTypeExpression class >> annotation [

	<MSEClass: #ByteTypeExpression super: #FASTJavaPrimitiveTypeExpression>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaByteTypeExpression class >> generatedSlotNames [
	<generated>
	'FASTJavaByteTypeExpression class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaByteTypeExpression class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaByteTypeExpression class >> requirements [

	<generated>
	^ {  }
]
