Class {
	#name : #FASTJavaSourceTextAnchor,
	#superclass : #FASTJavaSourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaSourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FASTJavaSourceAnchor>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]
