"
A character in Java code
"
Class {
	#name : #FASTJavaCharacterLiteral,
	#superclass : #FASTCharacterLiteral,
	#traits : 'FASTJavaTReceiver',
	#classTraits : 'FASTJavaTReceiver classTrait',
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaCharacterLiteral class >> annotation [

	<FMClass: #CharacterLiteral super: #FASTCharacterLiteral>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]
