Class {
	#name : #FASTJavaSourceTextAnchor,
	#superclass : #FASTJavaSourceAnchor,
	#traits : 'FamixTWithImmediateSource',
	#classTraits : 'FamixTWithImmediateSource classTrait',
	#category : #'FAST-Java-Model-Entities'
}

{ #category : #meta }
FASTJavaSourceTextAnchor class >> annotation [

	<MSEClass: #SourceTextAnchor super: #FASTJavaSourceAnchor>
	<package: #'FAST-Java-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaSourceTextAnchor class >> generatedSlotNames [
	<generated>
	'FASTJavaSourceTextAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaSourceTextAnchor class >> generatedTraitNames [
	<generated>
	^ #(FamixTWithImmediateSource)
]

{ #category : #meta }
FASTJavaSourceTextAnchor class >> requirements [

	<generated>
	^ {  }
]
